In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
sns.set()
import warnings
warnings.filterwarnings('ignore')
import datetime
import json
import re
import gensim
from gensim import corpora, models
from gensim.utils import simple_preprocess
from gensim.parsing.preprocessing import STOPWORDS
from nltk.stem import WordNetLemmatizer, SnowballStemmer
from nltk.stem.porter import *
import nltk
# nltk.download('wordnet')
import random
import multiprocessing
from collections import defaultdict
from gensim.models import Word2Vec
from nltk.corpus import stopwords
stopwords = set(stopwords.words('english'))

In [2]:
base_path = '/home/luxiaoling/wukun/MIND/data/'

In [3]:
columns = ['uid', 'impr_time', 'week', 'hour', 'relative_days', 'relative_hours', 'relative_seconds', 'history', 'cur_impr']
train_df = pd.read_csv(base_path+'behavior_sample_train.tsv', sep='\t', names=columns)
train_df.head()

,uid,impr_time,week,hour,relative_days,relative_hours,relative_seconds,history,cur_impr
0,U495159,2019-11-09 00:00:13,5,0,6,144,518387,N88765 N74317 N63723 N121794 N95711 N64341 N75...,N104437-0 N76810-0 N98657-0 N25492-0 N108809-0...
1,U251164,2019-11-09 00:00:24,5,0,6,144,518376,N42703 N126834 N118005 N13066 N43872 N48258 N1...,N79990-0 N59303-0 N65783-0 N18956-0 N2198-0 N9...
2,U515173,2019-11-09 00:00:25,5,0,6,144,518375,N10243 N14424 N55661 N114369 N70847 N123633 N8...,N4789-0 N17547-0 N104610-0 N37049-0 N92463-0 N...
3,U528649,2019-11-09 00:00:37,5,0,6,144,518363,N116996 N31266 N71082 N113593 N107137 N49262 N...,N2198-0 N79990-0 N18956-0 N119284-0 N92613-0 N...
4,U701987,2019-11-09 00:00:41,5,0,6,144,518359,N119674 N128483 N74723 N64141 N25892,N17456-0 N62003-0 N129463-0 N25492-0 N18956-0 ...

In [4]:
columns = ['uid', 'impr_time', 'week', 'hour', 'relative_days', 'relative_hours', 'relative_seconds', 'history', 'cur_impr']
val_df = pd.read_csv(base_path+'behavior_sample_val.tsv', sep='\t', names=columns)
val_df.head()

,uid,impr_time,week,hour,relative_days,relative_hours,relative_seconds,history,cur_impr
0,U129523,2019-11-15 00:00:10,4,0,0,-23,-86390,N65386 N100173 N3472 N4858 N16620 N125867 N132...,N82503-0 N80770-0 N32993-0 N62800-0 N83707-1 N...
1,U411819,2019-11-15 00:00:19,4,0,0,-23,-86381,N102152 N26417 N60132 N79285 N75220 N108312 N8...,N100425-0 N40742-0 N83707-0 N73303-0 N26122-0 ...
2,U450360,2019-11-15 00:00:27,4,0,0,-23,-86373,N81071 N126696 N87146 N84689 N59870,N26122-0 N78508-0 N68624-0 N82503-0 N118623-1 ...
3,U423393,2019-11-15 00:00:32,4,0,0,-23,-86368,N1396 N44611 N42796 N86153 N70947 N15206 N1064...,N56139-0 N96473-0 N45410-0 N121136-0 N63322-0 ...
4,U145343,2019-11-15 00:00:39,4,0,0,-23,-86361,N6306 N54797 N41484 N91923 N75819 N85123 N1764...,N14857-0 N104054-0 N110967-0 N121411-0 N121375...

In [5]:
with open(base_path+'new_user.csv', 'r') as f:
    new_user = f.readline().split()

In [7]:
with open(base_path+'new_news.csv', 'r') as f:
    new_news = f.readline().split()

In [11]:
all_users = list(set(train_df.uid) | set(val_df.uid))
user2idx = dict(zip(all_users, range(len(all_users))))

In [15]:
uid_news_dict = defaultdict(set)
all_news = set()
for uid, history, cur_impr in zip(train_df.uid, train_df.history, train_df.cur_impr):
    try:
        history_news = history.split()
    except:
        history_news = []
    all_news.update(history_news)
    uid_news_dict[uid].update(history_news)
    imprs = cur_impr.split()
    pos_news = list(filter(lambda x: x[-1] == '1', imprs))
    pos_news = [x[:-2] for x in pos_news]
    impr_news = [x[:-2] for x in imprs]
    all_news.update(impr_news)
    uid_news_dict[uid].update(pos_news)

In [16]:
for uid, history, cur_impr in zip(val_df.uid, val_df.history, val_df.cur_impr):
    try:
        history_news = history.split()
    except:
        history_news = []
    all_news.update(history_news)
    uid_news_dict[uid].update(history_news)
    imprs = cur_impr.split()
    pos_news = list(filter(lambda x: x[-1] == '1', imprs))
    pos_news = [x[:-2] for x in pos_news]
    impr_news = [x[:-2] for x in imprs]
    all_news.update(impr_news)
    uid_news_dict[uid].update(pos_news)

In [17]:
len(all_news)

78052

In [18]:
news2idx = dict(zip(all_news, range(len(all_news))))

In [19]:
news2idx

{'N96836': 0,
 'N92414': 1,
 'N9099': 2,
 'N91931': 3,
 'N112375': 4,
 'N26956': 5,
 'N101537': 6,
 'N85177': 7,
 'N38461': 8,
 'N4534': 9,
 'N48993': 10,
 'N128786': 11,
 'N44381': 12,
 'N46673': 13,
 'N469': 14,
 'N76198': 15,
 'N2591': 16,
 'N37921': 17,
 'N63603': 18,
 'N49001': 19,
 'N60860': 20,
 'N125348': 21,
 'N36304': 22,
 'N77561': 23,
 'N116939': 24,
 'N97898': 25,
 'N29911': 26,
 'N3649': 27,
 'N126811': 28,
 'N10656': 29,
 'N3938': 30,
 'N27101': 31,
 'N13844': 32,
 'N80983': 33,
 'N122005': 34,
 'N71074': 35,
 'N30828': 36,
 'N28655': 37,
 'N49657': 38,
 'N32861': 39,
 'N101773': 40,
 'N27047': 41,
 'N119850': 42,
 'N67475': 43,
 'N118880': 44,
 'N107367': 45,
 'N45875': 46,
 'N102657': 47,
 'N110821': 48,
 'N87115': 49,
 'N44473': 50,
 'N43873': 51,
 'N35607': 52,
 'N109195': 53,
 'N58780': 54,
 'N22317': 55,
 'N52278': 56,
 'N7551': 57,
 'N73750': 58,
 'N1761': 59,
 'N101609': 60,
 'N40062': 61,
 'N120282': 62,
 'N92808': 63,
 'N40512': 64,
 'N21309': 65,
 'N56879': 66,
 'N5873': 67,
 'N35725': 68,
 'N7407': 69,
 'N16438': 70,
 'N110373': 71,
 'N36374': 72,
 'N26372': 73,
 'N47864': 74,
 'N64713': 75,
 'N11432': 76,
 'N120229': 77,
 'N64665': 78,
 'N130217': 79,
 'N90713': 80,
 'N112091': 81,
 'N18753': 82,
 'N7290': 83,
 'N13525': 84,
 'N65802': 85,
 'N30529': 86,
 'N48630': 87,
 'N99809': 88,
 'N37920': 89,
 'N93962': 90,
 'N87853': 91,
 'N84481': 92,
 'N98238': 93,
 'N37862': 94,
 'N62393': 95,
 'N54991': 96,
 'N120303': 97,
 'N55686': 98,
 'N20889': 99,
 'N46391': 100,
 'N115006': 101,
 'N36422': 102,
 'N120291': 103,
 'N74018': 104,
 'N28980': 105,
 'N50922': 106,
 'N108361': 107,
 'N45104': 108,
 'N29163': 109,
 'N43252': 110,
 'N37761': 111,
 'N52145': 112,
 'N110829': 113,
 'N127322': 114,
 'N38733': 115,
 'N113986': 116,
 'N89275': 117,
 'N2012': 118,
 'N107625': 119,
 'N10715': 120,
 'N113846': 121,
 'N104330': 122,
 'N46638': 123,
 'N49285': 124,
 'N53519': 125,
 'N55583': 126,
 'N19629': 127,
 'N112758': 128,
 'N71333': 129,
 'N19456': 130,
 'N29773': 131,
 'N19162': 132,
 'N59235': 133,
 'N117961': 134,
 'N21603': 135,
 'N4564': 136,
 'N41244': 137,
 'N13162': 138,
 'N87170': 139,
 'N53630': 140,
 'N66183': 141,
 'N121167': 142,
 'N8977': 143,
 'N9141': 144,
 'N35332': 145,
 'N69117': 146,
 'N98187': 147,
 'N26707': 148,
 'N59612': 149,
 'N1323': 150,
 'N55661': 151,
 'N36937': 152,
 'N20412': 153,
 'N18207': 154,
 'N40593': 155,
 'N77356': 156,
 'N70472': 157,
 'N52804': 158,
 'N114253': 159,
 'N31675': 160,
 'N57708': 161,
 'N59463': 162,
 'N47479': 163,
 'N120035': 164,
 'N129055': 165,
 'N88917': 166,
 'N101948': 167,
 'N62158': 168,
 'N60180': 169,
 'N67793': 170,
 'N65175': 171,
 'N105596': 172,
 'N98034': 173,
 'N68703': 174,
 'N127479': 175,
 'N65447': 176,
 'N107801': 177,
 'N15651': 178,
 'N12594': 179,
 'N14589': 180,
 'N21935': 181,
 'N22237': 182,
 'N105684': 183,
 'N87218': 184,
 'N91690': 185,
 'N66527': 186,
 'N1311': 187,
 'N56620': 188,
 'N103110': 189,
 'N42945': 190,
 'N81525': 191,
 'N104096': 192,
 'N72925': 193,
 'N126586': 194,
 'N27325': 195,
 'N71648': 196,
 'N114968': 197,
 'N127834': 198,
 'N129349': 199,
 'N98977': 200,
 'N11747': 201,
 'N56089': 202,
 'N72782': 203,
 'N121340': 204,
 'N105552': 205,
 'N44604': 206,
 'N81719': 207,
 'N67529': 208,
 'N98412': 209,
 'N119969': 210,
 'N120806': 211,
 'N89448': 212,
 'N14122': 213,
 'N120926': 214,
 'N71534': 215,
 'N68221': 216,
 'N116840': 217,
 'N70391': 218,
 'N32012': 219,
 'N86753': 220,
 'N15746': 221,
 'N56753': 222,
 'N57111': 223,
 'N109872': 224,
 'N38132': 225,
 'N32206': 226,
 'N35095': 227,
 'N120266': 228,
 'N35869': 229,
 'N34904': 230,
 'N52809': 231,
 'N122698': 232,
 'N87330': 233,
 'N51344': 234,
 'N126564': 235,
 'N94280': 236,
 'N25757': 237,
 'N12525': 238,
 'N95090': 239,
 'N22546': 240,
 'N61825': 241,
 'N65240': 242,
 'N106325': 243,
 'N26599': 244,
 'N76024': 245,
 'N31667': 246,
 'N24668': 247,
 'N71231': 248,
 'N65974': 249,
 'N113090': 250,
 'N59539': 251,
 'N31081': 252,
 'N83219': 253,
 'N119862': 254,
 'N124797': 255,
 'N88148': 256,
 'N10651': 257,
 'N109355': 258,
 'N34799': 259,
 'N33937': 260,
 'N61599': 261,
 'N74819': 262,
 'N52363': 263,
 'N76681': 264,
 'N89139': 265,
 'N53493': 266,
 'N43373': 267,
 'N55571': 268,
 'N85752': 269,
 'N70008': 270,
 'N91010': 271,
 'N96063': 272,
 'N41977': 273,
 'N113388': 274,
 'N129131': 275,
 'N90702': 276,
 'N56864': 277,
 'N18568': 278,
 'N109291': 279,
 'N57925': 280,
 'N55241': 281,
 'N78896': 282,
 'N125364': 283,
 'N123822': 284,
 'N61663': 285,
 'N57727': 286,
 'N31645': 287,
 'N112720': 288,
 'N121325': 289,
 'N115618': 290,
 'N83609': 291,
 'N23555': 292,
 'N6825': 293,
 'N30567': 294,
 'N109877': 295,
 'N8292': 296,
 'N40192': 297,
 'N95883': 298,
 'N2503': 299,
 'N129813': 300,
 'N64402': 301,
 'N114393': 302,
 'N7665': 303,
 'N112831': 304,
 'N66765': 305,
 'N81717': 306,
 'N26612': 307,
 'N96498': 308,
 'N70244': 309,
 'N126239': 310,
 'N56299': 311,
 'N123284': 312,
 'N58376': 313,
 'N21546': 314,
 'N18154': 315,
 'N127863': 316,
 'N100412': 317,
 'N2794': 318,
 'N97374': 319,
 'N38938': 320,
 'N103760': 321,
 'N26509': 322,
 'N115619': 323,
 'N4036': 324,
 'N37726': 325,
 'N63731': 326,
 'N46452': 327,
 'N101918': 328,
 'N40547': 329,
 'N88723': 330,
 'N19337': 331,
 'N49062': 332,
 'N113737': 333,
 'N27486': 334,
 'N54419': 335,
 'N83632': 336,
 'N46833': 337,
 'N56205': 338,
 'N129915': 339,
 'N20804': 340,
 'N126723': 341,
 'N80944': 342,
 'N60644': 343,
 'N48798': 344,
 'N4664': 345,
 'N118383': 346,
 'N48638': 347,
 'N14575': 348,
 'N56396': 349,
 'N23036': 350,
 'N114584': 351,
 'N18980': 352,
 'N119274': 353,
 'N55061': 354,
 'N125500': 355,
 'N30016': 356,
 'N87868': 357,
 'N57114': 358,
 'N118748': 359,
 'N57761': 360,
 'N117813': 361,
 'N48560': 362,
 'N127879': 363,
 'N83145': 364,
 'N28593': 365,
 'N69807': 366,
 'N40993': 367,
 'N32234': 368,
 'N62059': 369,
 'N122483': 370,
 'N14807': 371,
 'N89387': 372,
 'N128794': 373,
 'N37889': 374,
 'N70675': 375,
 'N33660': 376,
 'N26698': 377,
 'N36019': 378,
 'N108947': 379,
 'N115226': 380,
 'N118567': 381,
 'N18079': 382,
 'N75504': 383,
 'N92295': 384,
 'N40987': 385,
 'N24607': 386,
 'N102719': 387,
 'N128535': 388,
 'N83740': 389,
 'N40348': 390,
 'N92876': 391,
 'N70050': 392,
 'N91550': 393,
 'N121946': 394,
 'N117516': 395,
 'N12004': 396,
 'N115001': 397,
 'N70143': 398,
 'N4668': 399,
 'N55424': 400,
 'N496': 401,
 'N32818': 402,
 'N47321': 403,
 'N26459': 404,
 'N2699': 405,
 'N18248': 406,
 'N46469': 407,
 'N80561': 408,
 'N39428': 409,
 'N108270': 410,
 'N5040': 411,
 'N94848': 412,
 'N106719': 413,
 'N102808': 414,
 'N26931': 415,
 'N28554': 416,
 'N37248': 417,
 'N109118': 418,
 'N55261': 419,
 'N71428': 420,
 'N117542': 421,
 'N125646': 422,
 'N58951': 423,
 'N79264': 424,
 'N30946': 425,
 'N97396': 426,
 'N19130': 427,
 'N45031': 428,
 'N59625': 429,
 'N8347': 430,
 'N93059': 431,
 'N51048': 432,
 'N21956': 433,
 'N14023': 434,
 'N112899': 435,
 'N1515': 436,
 'N32226': 437,
 'N28444': 438,
 'N107720': 439,
 'N39289': 440,
 'N51564': 441,
 'N81018': 442,
 'N112516': 443,
 'N27924': 444,
 'N86886': 445,
 'N81912': 446,
 'N20958': 447,
 'N27854': 448,
 'N8364': 449,
 'N125029': 450,
 'N16645': 451,
 'N85166': 452,
 'N9357': 453,
 'N1425': 454,
 'N119997': 455,
 'N69922': 456,
 'N88036': 457,
 'N23613': 458,
 'N67791': 459,
 'N66059': 460,
 'N104227': 461,
 'N17235': 462,
 'N107937': 463,
 'N45709': 464,
 'N67707': 465,
 'N68768': 466,
 'N110091': 467,
 'N64014': 468,
 'N5569': 469,
 'N24102': 470,
 'N10406': 471,
 'N3802': 472,
 'N47748': 473,
 'N114798': 474,
 'N82543': 475,
 'N13427': 476,
 'N59383': 477,
 'N114935': 478,
 'N79096': 479,
 'N68520': 480,
 'N40887': 481,
 'N91735': 482,
 'N80112': 483,
 'N44944': 484,
 'N24677': 485,
 'N4172': 486,
 'N116518': 487,
 'N88678': 488,
 'N58682': 489,
 'N66866': 490,
 'N85618': 491,
 'N130042': 492,
 'N93987': 493,
 'N20973': 494,
 'N111288': 495,
 'N97351': 496,
 'N9970': 497,
 'N84597': 498,
 'N298': 499,
 'N43228': 500,
 'N46449': 501,
 'N2324': 502,
 'N118733': 503,
 'N96763': 504,
 'N12558': 505,
 'N76255': 506,
 'N71219': 507,
 'N83319': 508,
 'N21082': 509,
 'N109240': 510,
 'N52708': 511,
 'N87365': 512,
 'N128998': 513,
 'N103686': 514,
 'N29706': 515,
 'N12702': 516,
 'N60239': 517,
 'N100479': 518,
 'N77067': 519,
 'N20524': 520,
 'N106287': 521,
 'N111044': 522,
 'N54558': 523,
 'N44660': 524,
 'N2548': 525,
 'N92996': 526,
 'N60070': 527,
 'N109700': 528,
 'N117518': 529,
 'N63222': 530,
 'N48482': 531,
 'N106770': 532,
 'N61934': 533,
 'N70359': 534,
 'N19540': 535,
 'N96006': 536,
 'N48263': 537,
 'N116521': 538,
 'N39376': 539,
 'N114913': 540,
 'N94197': 541,
 'N47932': 542,
 'N97512': 543,
 'N47193': 544,
 'N76387': 545,
 'N71130': 546,
 'N109468': 547,
 'N125533': 548,
 'N50240': 549,
 'N99469': 550,
 'N122494': 551,
 'N60052': 552,
 'N38798': 553,
 'N82056': 554,
 'N108730': 555,
 'N102930': 556,
 'N85987': 557,
 'N6909': 558,
 'N67008': 559,
 'N120239': 560,
 'N37487': 561,
 'N73535': 562,
 'N30412': 563,
 'N66245': 564,
 'N51598': 565,
 'N32004': 566,
 'N129921': 567,
 'N11493': 568,
 'N27695': 569,
 'N81390': 570,
 'N108001': 571,
 'N93921': 572,
 'N8121': 573,
 'N50707': 574,
 'N64822': 575,
 'N27199': 576,
 'N101980': 577,
 'N114446': 578,
 'N99570': 579,
 'N37703': 580,
 'N124408': 581,
 'N21995': 582,
 'N33412': 583,
 'N57002': 584,
 'N96101': 585,
 'N108904': 586,
 'N1974': 587,
 'N87849': 588,
 'N92831': 589,
 'N12873': 590,
 'N125396': 591,
 'N127833': 592,
 'N108760': 593,
 'N120091': 594,
 'N10300': 595,
 'N115076': 596,
 'N62603': 597,
 'N5862': 598,
 'N30120': 599,
 'N20585': 600,
 'N82032': 601,
 'N92879': 602,
 'N36332': 603,
 'N122955': 604,
 'N22529': 605,
 'N41278': 606,
 'N56491': 607,
 'N113556': 608,
 'N125412': 609,
 'N85470': 610,
 'N102610': 611,
 'N87496': 612,
 'N69005': 613,
 'N32483': 614,
 'N48802': 615,
 'N46977': 616,
 'N107778': 617,
 'N47374': 618,
 'N98371': 619,
 'N6850': 620,
 'N98102': 621,
 'N122958': 622,
 'N73646': 623,
 'N88975': 624,
 'N89484': 625,
 'N5713': 626,
 'N122743': 627,
 'N48381': 628,
 'N19740': 629,
 'N106563': 630,
 'N105647': 631,
 'N46610': 632,
 'N66981': 633,
 'N58700': 634,
 'N1478': 635,
 'N95787': 636,
 'N45128': 637,
 'N78036': 638,
 'N10721': 639,
 'N112969': 640,
 'N88671': 641,
 'N123198': 642,
 'N74323': 643,
 'N60394': 644,
 'N58742': 645,
 'N87516': 646,
 'N29105': 647,
 'N108013': 648,
 'N82779': 649,
 'N106708': 650,
 'N84886': 651,
 'N95162': 652,
 'N2214': 653,
 'N63865': 654,
 'N16716': 655,
 'N124344': 656,
 'N75282': 657,
 'N37643': 658,
 'N109933': 659,
 'N83203': 660,
 'N21106': 661,
 'N46125': 662,
 'N118330': 663,
 'N124322': 664,
 'N127832': 665,
 'N74680': 666,
 'N52877': 667,
 'N127361': 668,
 'N114894': 669,
 'N103006': 670,
 'N116319': 671,
 'N47027': 672,
 'N100104': 673,
 'N29659': 674,
 'N16821': 675,
 'N90290': 676,
 'N62945': 677,
 'N94577': 678,
 'N61786': 679,
 'N104645': 680,
 'N76247': 681,
 'N54231': 682,
 'N122449': 683,
 'N127933': 684,
 'N41890': 685,
 'N64175': 686,
 'N44328': 687,
 'N37093': 688,
 'N18014': 689,
 'N124391': 690,
 'N7458': 691,
 'N122662': 692,
 'N6049': 693,
 'N124972': 694,
 'N98395': 695,
 'N3390': 696,
 'N117274': 697,
 'N107145': 698,
 'N74557': 699,
 'N80027': 700,
 'N64968': 701,
 'N95473': 702,
 'N36791': 703,
 'N67451': 704,
 'N71535': 705,
 'N66072': 706,
 'N81028': 707,
 'N102952': 708,
 'N38708': 709,
 'N111000': 710,
 'N116374': 711,
 'N94072': 712,
 'N34146': 713,
 'N93896': 714,
 'N46623': 715,
 'N108511': 716,
 'N58255': 717,
 'N129449': 718,
 'N11288': 719,
 'N37319': 720,
 'N4180': 721,
 'N100263': 722,
 'N55772': 723,
 'N39572': 724,
 'N116100': 725,
 'N50013': 726,
 'N94459': 727,
 'N16895': 728,
 'N35834': 729,
 'N85401': 730,
 'N24366': 731,
 'N2922': 732,
 'N56639': 733,
 'N66986': 734,
 'N4579': 735,
 'N45077': 736,
 'N45542': 737,
 'N10236': 738,
 'N27679': 739,
 'N52222': 740,
 'N117437': 741,
 'N108099': 742,
 'N106346': 743,
 'N95333': 744,
 'N117719': 745,
 'N67231': 746,
 'N99433': 747,
 'N40300': 748,
 'N119675': 749,
 'N58846': 750,
 'N36202': 751,
 'N39837': 752,
 'N11658': 753,
 'N76008': 754,
 'N63463': 755,
 'N112642': 756,
 'N84247': 757,
 'N97143': 758,
 'N79023': 759,
 'N65041': 760,
 'N19471': 761,
 'N13845': 762,
 'N59883': 763,
 'N114583': 764,
 'N35392': 765,
 'N127978': 766,
 'N127219': 767,
 'N58652': 768,
 'N9473': 769,
 'N123738': 770,
 'N67093': 771,
 'N119541': 772,
 'N33725': 773,
 'N56126': 774,
 'N106195': 775,
 'N56367': 776,
 'N119881': 777,
 'N127984': 778,
 'N32019': 779,
 'N125179': 780,
 'N24894': 781,
 'N124527': 782,
 'N81188': 783,
 'N187': 784,
 'N22462': 785,
 'N92310': 786,
 'N126614': 787,
 'N7179': 788,
 'N47662': 789,
 'N116734': 790,
 'N13094': 791,
 'N125871': 792,
 'N23614': 793,
 'N64877': 794,
 'N88310': 795,
 'N23152': 796,
 'N1543': 797,
 'N125037': 798,
 'N81662': 799,
 'N85471': 800,
 'N59583': 801,
 'N128164': 802,
 'N97257': 803,
 'N88503': 804,
 'N10753': 805,
 'N123722': 806,
 'N119634': 807,
 'N11045': 808,
 'N126086': 809,
 'N1153': 810,
 'N115632': 811,
 'N97738': 812,
 'N124603': 813,
 'N44544': 814,
 'N122424': 815,
 'N14138': 816,
 'N93576': 817,
 'N61050': 818,
 'N109438': 819,
 'N21624': 820,
 'N36288': 821,
 'N38329': 822,
 'N7906': 823,
 'N71837': 824,
 'N19985': 825,
 'N46361': 826,
 'N91886': 827,
 'N64007': 828,
 'N38901': 829,
 'N38129': 830,
 'N128479': 831,
 'N97081': 832,
 'N2244': 833,
 'N24888': 834,
 'N16209': 835,
 'N126068': 836,
 'N2800': 837,
 'N80579': 838,
 'N59989': 839,
 'N22127': 840,
 'N61119': 841,
 'N62012': 842,
 'N101930': 843,
 'N25236': 844,
 'N61209': 845,
 'N52266': 846,
 'N99685': 847,
 'N105306': 848,
 'N72596': 849,
 'N28435': 850,
 'N56684': 851,
 'N122388': 852,
 'N11778': 853,
 'N14044': 854,
 'N89318': 855,
 'N13342': 856,
 'N78759': 857,
 'N127619': 858,
 'N18387': 859,
 'N27736': 860,
 'N4257': 861,
 'N54038': 862,
 'N45023': 863,
 'N117682': 864,
 'N85204': 865,
 'N54663': 866,
 'N91575': 867,
 'N108706': 868,
 'N80709': 869,
 'N71022': 870,
 'N63116': 871,
 'N114675': 872,
 'N72202': 873,
 'N17573': 874,
 'N70806': 875,
 'N89118': 876,
 'N43737': 877,
 'N26091': 878,
 'N22389': 879,
 'N79341': 880,
 'N53353': 881,
 'N125309': 882,
 'N56045': 883,
 'N14084': 884,
 'N32871': 885,
 'N100512': 886,
 'N74009': 887,
 'N101818': 888,
 'N60421': 889,
 'N27341': 890,
 'N54461': 891,
 'N122536': 892,
 'N29041': 893,
 'N13316': 894,
 'N34256': 895,
 'N91352': 896,
 'N114991': 897,
 'N98396': 898,
 'N7214': 899,
 'N94180': 900,
 'N25382': 901,
 'N81229': 902,
 'N70938': 903,
 'N34899': 904,
 'N59113': 905,
 'N18945': 906,
 'N56086': 907,
 'N114559': 908,
 'N95615': 909,
 'N125345': 910,
 'N126565': 911,
 'N93944': 912,
 'N50737': 913,
 'N53267': 914,
 'N39095': 915,
 'N105159': 916,
 'N6158': 917,
 'N66425': 918,
 'N57662': 919,
 'N124163': 920,
 'N72066': 921,
 'N12209': 922,
 'N96610': 923,
 'N5102': 924,
 'N130257': 925,
 'N35626': 926,
 'N1774': 927,
 'N52011': 928,
 'N31244': 929,
 'N70617': 930,
 'N84068': 931,
 'N117391': 932,
 'N98906': 933,
 'N68435': 934,
 'N22454': 935,
 'N124934': 936,
 'N44646': 937,
 'N4062': 938,
 'N88497': 939,
 'N25163': 940,
 'N91024': 941,
 'N27355': 942,
 'N109496': 943,
 'N114315': 944,
 'N113417': 945,
 'N18966': 946,
 'N116176': 947,
 'N123405': 948,
 'N76571': 949,
 'N35702': 950,
 'N116200': 951,
 'N66193': 952,
 'N99400': 953,
 'N21902': 954,
 'N71923': 955,
 'N27991': 956,
 'N45905': 957,
 'N82711': 958,
 'N84324': 959,
 'N26565': 960,
 'N127299': 961,
 'N104940': 962,
 'N42497': 963,
 'N127025': 964,
 'N56819': 965,
 'N21125': 966,
 'N123818': 967,
 'N83824': 968,
 'N93748': 969,
 'N41896': 970,
 'N121269': 971,
 'N112048': 972,
 'N110187': 973,
 'N9148': 974,
 'N3277': 975,
 'N84191': 976,
 'N48636': 977,
 'N86204': 978,
 'N60924': 979,
 'N98865': 980,
 'N19646': 981,
 'N22496': 982,
 'N10769': 983,
 'N87': 984,
 'N73656': 985,
 'N31102': 986,
 'N54816': 987,
 'N127631': 988,
 'N124941': 989,
 'N58588': 990,
 'N68583': 991,
 'N12328': 992,
 'N113297': 993,
 'N104570': 994,
 'N56537': 995,
 'N122867': 996,
 'N109254': 997,
 'N24950': 998,
 'N66022': 999,
 ...}

In [26]:
save_path = '/home/luxiaoling/wukun/pinsage/data/'

In [27]:
with open(save_path+'user2idx.json', 'w') as f:
    json.dump(user2idx, f, indent=4)

In [28]:
with open(save_path+'news2idx.json', 'w') as f:
    json.dump(news2idx, f, indent=4)

In [29]:
user2news = {k: '_'.join(v) for k, v in uid_news_dict.items()}

In [30]:
with open(save_path+'user2news.json', 'w') as f:
    json.dump(user2news, f, indent=4)